// <auto-generated />
namespace DesktopProject_V3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UP2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UP2));
        
        string IMigrationMetadata.Id
        {
            get { return "202304181554332_UP2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
